### ISSUE TITLE
actuator fields conflicting with eachother

### ISSUE THREAD

**Issue by tyoungNIO** [nio-blocks/raspi_gpio#4]
In a WriteGPIO block I have two pins configured, pin 7 actuator is {{$red}} and pin 20 actuator is {{$yellow}}. Input signals from subscriber are booleans, one attribute per signal, e.g. {{$red: True}}

 {{$red: True}} evaluates at the {{$yellow}} actuator as False, and vice-a-versa

Workaround is to configure pin actuators as {{$.red}} and {{$.yellow}}, but this causes extra logging:
NIO [ERROR] [xcom_endpoint.gpio_7_20] Error evaluating actuator expression: AttributeError: 'Signal' object has no attribute 'red'

Issue reproducible on BeagleBoneBlack (Broomfield LAN .128), likely on other pi-compatible devices, as well.

**Comment by mattdodge** [comment]
To prevent the logging, you'll want to do something like this in your block config instead of `$red`.

```
{{ getattr($, 'red', False) }}
```

That will get `$red` if it exists, but if it doesn't it should return `False`. If that doesn't work go ahead and re-open the issue.

**Comment by tyoungNIO** [comment]
Nice, thanks, Matt. I'll try that out.
